version: "3"

services:
  php-fpm:
    build:
      context: .docker/php-fpm
    volumes:
      - ./:/app
      - .docker/php-fpm/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - .docker/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .docker/php-fpm/docker-php-custom-settings.ini:/usr/local/etc/php/conf.d/docker-php-custom-settings.ini
    working_dir: /app
    environment:
      - OPCACHE_ENABLED=${OPCACHE_ENABLED}

#  php-fpm-queue:
#    restart: always
#    build:
#      context: .docker/php-fpm
#    volumes:
#      - ./:/app
#    working_dir: /app
#    command: php artisan queue:work --tries=3 --delay=5 --timeout=120

#  php-fpm-schedule:
#    restart: always
#    build:
#      context: .docker/php-fpm
#    volumes:
#      - ./:/app
#      - .docker/php-fpm-schedule/scheduler.sh:/usr/local/bin/scheduler.sh
#    working_dir: /app
#    command: scheduler.sh

  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./:/app
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  postgres:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: simple_catalog
      POSTGRES_PASSWORD: simple_catalog
      POSTGRES_DB: simple_catalog
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    command: redis-server
    ports:
      - "6379:6379"

#  nodejs-mix:
#    image: node:19-alpine
#    restart: always
#    working_dir: /app
#    volumes:
#      - ./:/app
#    command: sh -c "npm install && npm run watch"

volumes:
  db-data:
  redis-data:
